# site
title: Walter Bolitto
baseurl: "/posts"
url: "http:/bolitto.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: 

# bio
header: Walter Bolitto
desc: >
  Educação, Tecnologia e Política
# posts
date_format: "%Y"
post_title: Artigo
post_date: Ano
post_cat: Categoria

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
